project_id = "mpmohxwufmgmenmggbup"

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.get-maps-config]
verify_jwt = false

[functions.ai-twin-chat]
verify_jwt = false